services:
    path: /
    controller: App\Controller\PersonalAccountController::myServices

transactions:
    path: /transactions
    controller: App\Controller\PersonalAccountController::myTransactions

deleteservice:
    path: /deleteservice/{id}
    controller: App\Controller\PersonalAccountController::deleteService

settlementday:
    path: /settlement-day
    controller: App\Controller\PersonalAccountController::settlementDay
